### ISSUE TITLE
Error in windows 10 . Sample don't work. Childprocess error

### ISSUE THREAD

**Issue by brakdag** [breizoreol/spoticly#1]
D:\temp> spoticly artist radiohead

- I found 14 albums !

   OK Computer OKNOTOK 1997 2017 (album - 2017)
   A Moon Shaped Pool (album - 2016)
   TKOL RMX 1234567 (album - 2011)
   The King Of Limbs (album - 2011)
   In Rainbows (album - 2007)
   In Rainbows Disk 2 (album - 2007)
   Com Lag: 2+2=5 (album - 2004)
   Hail To the Thief (album - 2003)
   Amnesiac (album - 2001)
   I Might Be Wrong (album - 2001)
   Kid A (album - 2000)
   OK Computer (album - 1997)
   The Bends (album - 1995)
   Pablo Honey (album - 1993)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn osascript ENOENT
    at _errnoException (util.js:992:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by matthieu-rolland** [comment]
Hello,

Are you trying this on windows?  As stated in the README, spoticly only works on MAC OS for now.

This is because the part that controls spotify uses applescript internally;  I'm not sure how I will implement something similar on windows and linux, but I'm thinking about it.
